from handlers.common import register_handlers_common
from handlers.choose_course import register_handlers_course
from handlers.moderator import register_handlers_upload_course
from handlers.admin_login import register_handlers_admin_log

